matrix:
  include:
    - os: osx
      language: node_js
      node_js: "8"
    - os: linux
      language: generic
      services: docker

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run build:linux
    else
      npm run build:osx
    fi
